### ISSUE TITLE
Unable to send Mantis bug report via HTTPS.

### ISSUE THREAD

**Issue by drewsilcock** [soygul/NBug#80]
When trying to send a Mantis bug report over HTTPS, the following exception occurs:

**Exception**: System.ArgumentException
**Message**: The provided URI scheme 'https' is invalid; expected 'http'. Parameter name: via
**Target Site** Void ValidateScheme(System.Uri) @ System.ServiceModel.Channels.TransportChannelFactory`1[TChannel]
**Source**: System.ServiceModel
**ParamName**: via
**HResult**: -2147024809
**Stack Trace**:

```csharp
at System.ServiceModel.Channels.TransportChannelFactory`1.ValidateScheme(Uri via)
   at System.ServiceModel.Channels.HttpChannelFactory`1.ValidateCreateChannelParameters(EndpointAddress remoteAddress, Uri via)
   at System.ServiceModel.Channels.HttpChannelFactory`1.OnCreateChannelCore(EndpointAddress remoteAddress, Uri via)
   at System.ServiceModel.Channels.HttpChannelFactory`1.OnCreateChannel(EndpointAddress remoteAddress, Uri via)
   at System.ServiceModel.Channels.ChannelFactoryBase`1.InternalCreateChannel(EndpointAddress address, Uri via)
   at System.ServiceModel.Channels.ChannelFactoryBase`1.CreateChannel(EndpointAddress address, Uri via)
   at System.ServiceModel.Channels.ServiceChannelFactory.ServiceChannelFactoryOverRequest.CreateInnerChannelBinder(EndpointAddress to, Uri via)
   at System.ServiceModel.Channels.ServiceChannelFactory.CreateServiceChannel(EndpointAddress address, Uri via)
   at System.ServiceModel.Channels.ServiceChannelFactory.CreateChannel(Type channelType, EndpointAddress address, Uri via)
   at System.ServiceModel.ChannelFactory`1.CreateChannel(EndpointAddress address, Uri via)
   at System.ServiceModel.ChannelFactory`1.CreateChannel()
   at System.ServiceModel.ClientBase`1.CreateChannel()
   at System.ServiceModel.ClientBase`1.CreateChannelInternal()
   at System.ServiceModel.ClientBase`1.get_Channel()
   at NBug.Core.Submission.Tracker.Mantis.MantisConnectService.mc_login(String username, String password)
   at NBug.Core.Submission.Tracker.Mantis.Mantis.Send(String fileName, Stream file, Report report, SerializableException exception)
   at NBug.Core.Submission.Dispatcher.EnumerateDestinations(Stream reportFile, ExceptionData exceptionData)
```

As MantisHub (sensibly) redirects HTTP to HTTPS, trying to submit a bug report sends back a redirect, which is of course an empty response. This causes the following exception to occur:

**Exception**: System.ServiceModel.ProtocolException
**Message**: The content type text/html of the response message does not match the content type of the binding (text/xml; charset=utf-8). If using a custom encoder, be sure that the IsContentTypeSupported method is implemented properly. The first 0 bytes of the response were: ''.
**Target Site** Void HandleReturnMessage(System.Runtime.Remoting.Messaging.IMessage, System.Runtime.Remoting.Messaging.IMessage) @ System.Runtime.Remoting.Proxies.RealProxy
**Source**: mscorlib
**ParamName**: via
**HResult**: -2146233087
**Stack Trace**:

```cs

Server stack trace: 
   at System.ServiceModel.Channels.HttpChannelUtilities.ValidateRequestReplyResponse(HttpWebRequest request, HttpWebResponse response, HttpChannelFactory`1 factory, WebException responseException, ChannelBinding channelBinding)
   at System.ServiceModel.Channels.HttpChannelFactory`1.HttpRequestChannel.HttpChannelRequest.WaitForReply(TimeSpan timeout)
   at System.ServiceModel.Channels.RequestChannel.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Dispatcher.RequestChannelBinder.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at NBug.Core.Submission.Tracker.Mantis.IMantisConnectService.mc_login(String username, String password)
   at NBug.Core.Submission.Tracker.Mantis.MantisConnectService.mc_login(String username, String password)
   at NBug.Core.Submission.Tracker.Mantis.Mantis.Send(String fileName, Stream file, Report report, SerializableException exception)
   at NBug.Core.Submission.Dispatcher.EnumerateDestinations(Stream reportFile, ExceptionData exceptionData)
```

**Comment by soygul** [comment]
I don't have the implementation details. If @shaxxx is still using it, he can comment.

Otherwise implementation details are here if anyone wants to go on a bug-hunt: https://github.com/soygul/NBug/tree/master/NBug/Core/Submission/Tracker/Mantis

**Comment by shaxxx** [comment]
Well my first guess would be that problem is [HERE](https://github.com/soygul/NBug/blob/master/NBug/Core/Submission/Tracker/Mantis/Mantis.cs#L181)
Service uses BasicHttpBinding internally which accoriding to [MSDN](https://msdn.microsoft.com/en-us/library/ms729700(v=vs.110).aspx) does not support security by default.

Solution would be to detect protocol from link (http or https) and create Binding accordingly. Or even better add user inject/configure non default binding if he wants to.  Unfortunately my time is currently limited.

**Comment by drewsilcock** [comment]
Thanks for the swift response. Is it possible that all you need to do is simply specify the `Security` property of the `BasicHttpBinding` to `Transport`? I've modified the [line in question](https://github.com/soygul/NBug/blob/master/NBug/Core/Submission/Tracker/Mantis/Mantis.cs#L181) as below based on [this MSDN example](https://msdn.microsoft.com/en-us/library/ms731334(v=vs.110).aspx#code-snippet-2), is there an easy way to test the report sending?

```csharp
var binding = new BasicHttpBinding();
binding.Security.Mode = BasicHttpSecurityMode.Transport;
binding.Security.Transport.ClientCredentialType = HttpClientCredentialType.None;
binding.Security.Transport.ProxyCredentialType = HttpProxyCredentialType.None;

var service = new MantisConnectService(binding, new EndpointAddress(Url));
```

**Comment by soygul** [comment]
You can create a simple CLI test app that throws an exception as soon as it starts.

You can try to load the config file and hit the test button. It may or may not work with Mantis though.

**Comment by shaxxx** [comment]
@drewsilcock this looks good to me if you don't mind hard-coding it to always use HTTPS. Actual public solution needs to keep in mind people using good old http.
And since I have no way to test this keep in mind that I'm just guessing here, and maybe actual error doesn't have nothing to do with specified line. If you have some kind of test account I could take a look. My Mantis web doesn't have SSL.

**Comment by drewsilcock** [comment]
I tested this change on HTTPS and it works absolutely fine. As far as choosing between HTTPS and HTTP binding, it should be as simple as:

```csharp
var tlsBinding = new BasicHttpBinding();
tlsBinding.Security.Mode = BasicHttpSecurityMode.Transport;
tlsBinding.Security.Transport.ClientCredentialType = HttpClientCredentialType.None;
tlsBinding.Security.Transport.ProxyCredentialType = HttpProxyCredentialType.None;

bool shouldUseTls = Url.StartsWith("https");

var service = new MantisConnectService(shouldUseTls ? tlsBinding : new BasicHttpBinding(), new EndpointAddress(Url));
```

This wouldn't solve the problem of the HTTP -> HTTPS redirect triggering an exception, but that seems more corollary to the whole HTTPS binding issue.

As my Mantis instance redirects HTTP to HTTPS, I'm not able to test HTTP with the above changes. If I commit these changes to a new branch, would you be able to test it with your HTTP Mantis instance?

**Comment by biship** [comment]
Drew, I get this error with your change:

```
NBugTrace: 12:24:49  : Submitting bug report via Mantis.
NBugError: 12:24:49  : An exception occurred while submitting bug report with Mantis. Check the inner exception for details.
Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at NBug.Core.Reporting.Info.Report.ToString() in D:\Code\Other\NBug-master\NBug\Core\Reporting\Info\Report.cs:line 52
   at NBug.Core.Submission.Tracker.Mantis.Mantis.Send(String fileName, Stream file, Report report, SerializableException exception) in D:\Code\Other\NBug-master\NBug\Core\Submission\Tracker\Mantis\Mantis.cs:line 177
   at NBug.Core.Submission.Dispatcher.EnumerateDestinations(Stream reportFile, ExceptionData exceptionData) in D:\Code\Other\NBug-master\NBug\Core\Submission\Dispatcher.cs:line 133
```
